os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - name="frappe-base"
  - image="monogramm/docker-frappe-base:${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}/${VARIANT}"

script:
  # Test container build
  - travis_wait docker build -t "$image" "$dir"
  - docker images
  - docker images | grep "monogramm/docker-frappe-base"

after_script:
  # Test container run
  - docker run --name "$name" -d "$image"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=2.7 VARIANT=alpine
    - env: VERSION=2.7 VARIANT=slim-buster
    - env: VERSION=2.7 VARIANT=buster

env: # Environments
    - VERSION=2.7 VARIANT=alpine
    - VERSION=3.5 VARIANT=alpine
    - VERSION=3.6 VARIANT=alpine
    - VERSION=3.7 VARIANT=alpine
    - VERSION=3.8 VARIANT=alpine
    - VERSION=2.7 VARIANT=slim-buster
    - VERSION=3.5 VARIANT=slim-buster
    - VERSION=3.6 VARIANT=slim-buster
    - VERSION=3.7 VARIANT=slim-buster
    - VERSION=3.8 VARIANT=slim-buster
    - VERSION=2.7 VARIANT=buster
    - VERSION=3.5 VARIANT=buster
    - VERSION=3.6 VARIANT=buster
    - VERSION=3.7 VARIANT=buster
    - VERSION=3.8 VARIANT=buster
